window.SITE_CONFIG = {
  companyName: "WildGuard Removal",
  companyLegalName: "WildGuard Removal Services LLC",
  companyId: "ID WG-2046-118",
  website: "www.wildguardremoval.com",
  phone: "+15550194720",
  phoneDisplay: "+1 (555) 019-4720",
  phoneButtonLabel: "Call Wildlife Help",
  email: "help@wildguardremoval.com",
  addressLine1: "1847 Cedar Ridge Parkway",
  addressLine2: "Asheville, NC 28801",
  serviceArea: "Asheville, Hendersonville, Black Mountain, and nearby mountain communities",
  businessHours: "24/7 emergency response, scheduled inspections Mon-Sat",
  footerTextPrimary: "Humane wildlife removal, exclusion repairs, sanitation, and long-term prevention for homes and small businesses.",
  footerTextSecondary: "Independent local providers handle inspections and field work. Customers should verify licensing, insurance, and credentials before hiring.",
  disclaimerShort: "Free matching service for wildlife removal inquiries. Providers are independent and work is not guaranteed by this website.",
  disclaimerFull: "Disclaimer: This site is a free service to assist users/customers in connecting with local wildlife removal service providers. All contractors/providers are independent and this site does not warrant or guarantee any work performed. It is the responsibility of the customer to verify that the hired contractor/provider furnishes the necessary license, insurance, certification, or other credentials required for the work being performed. All persons depicted in a photo or video are actors or models and not contractors/providers listed on this site.",
  footerDisclaimer: "This website helps visitors request wildlife removal information and connect with independent local providers. We do not perform field work, set final prices, or guarantee any provider's services.",
  copyrightLine: "Copyright 2026 WildGuard Removal. All rights reserved.",
  ctaPrimary: "Schedule Inspection",
  ctaSecondary: "Explore Services",
  formSuccessLead: "Thanks. Your wildlife removal request was received.",
  formSuccessDetail: "A coordinator for {company} will review your message and may contact you from {email}."
};
